name: Build and push nearspark docker images

on:
  push:
    branches: [ develop ]
    paths: 
    - '**Dockerfile'
    - 'src/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push producers
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/producers/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nearspark-producers:latest
          
      - name: Build and push processors
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/processors/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nearspark-processors:latest
